### PR TITLE
Add Ruby versions & Use container-based infrastructure

### PR DESCRIPTION
**Pull request by yuya-takeyama**
@woothee/owners 

Please review and merge.

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
Hmm, seems related with https://github.com/bundler/bundler/pull/3559.
Updating bundler may resolve this issue, I believe. https://github.com/google/google-api-ruby-client/pull/322

**Comment by yuya-takeyama** [comment]
Now mergeable!

**Comment by tagomoris** [comment]
@yuya-takeyama could you remove `1.9` from versions?
It's already not supported by ruby dev community.

**Comment by yuya-takeyama** [comment]
@tagomoris 
Okay, removed.

**Comment by tagomoris** [comment]
:+1:

**Pull request merged**
