### PR TITLE
Add Ruby version

### PR DESCRIPTION
**Pull request by yuya-takeyama**
@woothee/owners :pray:

### CODE REVIEW

**Comment by yuya-takeyama** [comment]
:disappointed: 
image

**Comment by yuya-takeyama** [comment]
Now the tests passed!
We need to specify as not `2.3` but `2.3.0`... https://github.com/woothee/woothee-ruby/commit/ce7c9bdd0d292658f3a8ba5fdab2720f541627fd

**Comment by yuya-takeyama** [comment]
Thanks to @ykzts!
https://twitter.com/ykzts/status/697016453317337088

**Comment by tagomoris** [comment]
Nice patch. Thanks!

**Pull request merged**
